insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-20', 17, 'https://nature.com/vestibulum/aliquet/ultrices.xml?leo=amet&odio=erat&porttitor=nulla&id=tempus&consequat=vivamus&in=in&consequat=felis&ut=eu&nulla=sapien&sed=cursus&accumsan=vestibulum&felis=proin&ut=eu&at=mi&dolor=nulla&quis=ac&odio=enim&consequat=in&varius=tempor&integer=turpis&ac=nec&leo=euismod&pellentesque=scelerisque&ultrices=quam&mattis=turpis&odio=adipiscing&donec=lorem&vitae=vitae&nisi=mattis&nam=nibh&ultrices=ligula&libero=nec&non=sem&mattis=duis&pulvinar=aliquam&nulla=convallis&pede=nunc&ullamcorper=proin&augue=at&a=turpis&suscipit=a&nulla=pede&elit=posuere&ac=nonummy&nulla=integer&sed=non&vel=velit&enim=donec&sit=diam', 'Created', 1, 1, 1);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-16', 28, 'https://google.co.uk/lacus/morbi/sem/mauris/laoreet/ut/rhoncus.json?vestibulum=aliquam&ante=convallis&ipsum=nunc&primis=proin&in=at&faucibus=turpis&orci=a&luctus=pede&et=posuere&ultrices=nonummy&posuere=integer&cubilia=non&curae=velit&nulla=donec&dapibus=diam&dolor=neque&vel=vestibulum&est=eget&donec=vulputate&odio=ut&justo=ultrices&sollicitudin=vel&ut=augue', 'Created', 2, 2, 2);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-18', 22, 'https://people.com.cn/id/luctus/nec/molestie.jpg?ac=arcu&neque=adipiscing&duis=molestie&bibendum=hendrerit&morbi=at&non=vulputate&quam=vitae&nec=nisl&dui=aenean&luctus=lectus&rutrum=pellentesque&nulla=eget&tellus=nunc&in=donec&sagittis=quis&dui=orci&vel=eget&nisl=orci&duis=vehicula&ac=condimentum&nibh=curabitur&fusce=in&lacus=libero&purus=ut&aliquet=massa&at=volutpat&feugiat=convallis&non=morbi&pretium=odio&quis=odio&lectus=elementum&suspendisse=eu&potenti=interdum&in=eu&eleifend=tincidunt&quam=in&a=leo&odio=maecenas&in=pulvinar&hac=lobortis&habitasse=est&platea=phasellus&dictumst=sit&maecenas=amet&ut=erat&massa=nulla&quis=tempus&augue=vivamus', 'Created', 3, 3, 3);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-22', 23, 'https://gizmodo.com/mauris/lacinia/sapien/quis/libero.jpg?nisl=etiam&nunc=vel&nisl=augue&duis=vestibulum&bibendum=rutrum&felis=rutrum&sed=neque&interdum=aenean&venenatis=auctor&turpis=gravida&enim=sem&blandit=praesent&mi=id&in=massa&porttitor=id&pede=nisl&justo=venenatis&eu=lacinia&massa=aenean&donec=sit&dapibus=amet&duis=justo&at=morbi&velit=ut&eu=odio&est=cras&congue=mi&elementum=pede&in=malesuada&hac=in&habitasse=imperdiet&platea=et&dictumst=commodo&morbi=vulputate&vestibulum=justo&velit=in&id=blandit&pretium=ultrices&iaculis=enim&diam=lorem&erat=ipsum&fermentum=dolor&justo=sit&nec=amet&condimentum=consectetuer&neque=adipiscing&sapien=elit&placerat=proin&ante=interdum&nulla=mauris&justo=non&aliquam=ligula&quis=pellentesque&turpis=ultrices&eget=phasellus&elit=id&sodales=sapien&scelerisque=in&mauris=sapien&sit=iaculis&amet=congue&eros=vivamus&suspendisse=metus&accumsan=arcu&tortor=adipiscing&quis=molestie&turpis=hendrerit&sed=at&ante=vulputate&vivamus=vitae&tortor=nisl&duis=aenean&mattis=lectus&egestas=pellentesque&metus=eget&aenean=nunc&fermentum=donec&donec=quis&ut=orci&mauris=eget&eget=orci&massa=vehicula&tempor=condimentum&convallis=curabitur&nulla=in&neque=libero&libero=ut&convallis=massa&eget=volutpat&eleifend=convallis&luctus=morbi&ultricies=odio&eu=odio&nibh=elementum&quisque=eu&id=interdum&justo=eu&sit=tincidunt&amet=in&sapien=leo', 'Created', 4, 4, 4);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-20', 21, 'https://sun.com/vestibulum/aliquet/ultrices/erat.json?mauris=ultrices&laoreet=libero&ut=non&rhoncus=mattis&aliquet=pulvinar&pulvinar=nulla&sed=pede&nisl=ullamcorper&nunc=augue&rhoncus=a&dui=suscipit&vel=nulla&sem=elit&sed=ac&sagittis=nulla&nam=sed&congue=vel&risus=enim&semper=sit&porta=amet&volutpat=nunc&quam=viverra&pede=dapibus&lobortis=nulla&ligula=suscipit&sit=ligula&amet=in&eleifend=lacus&pede=curabitur&libero=at&quis=ipsum&orci=ac&nullam=tellus', 'Created', 5, 1, 5);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-16', 20, 'https://wikia.com/posuere.png?massa=vestibulum&quis=sit&augue=amet&luctus=cursus&tincidunt=id&nulla=turpis&mollis=integer&molestie=aliquet&lorem=massa&quisque=id&ut=lobortis&erat=convallis&curabitur=tortor&gravida=risus&nisi=dapibus&at=augue&nibh=vel&in=accumsan&hac=tellus&habitasse=nisi&platea=eu&dictumst=orci&aliquam=mauris&augue=lacinia&quam=sapien&sollicitudin=quis&vitae=libero&consectetuer=nullam&eget=sit&rutrum=amet&at=turpis&lorem=elementum&integer=ligula&tincidunt=vehicula&ante=consequat&vel=morbi&ipsum=a&praesent=ipsum&blandit=integer&lacinia=a&erat=nibh&vestibulum=in&sed=quis&magna=justo&at=maecenas&nunc=rhoncus&commodo=aliquam&placerat=lacus&praesent=morbi&blandit=quis&nam=tortor&nulla=id&integer=nulla&pede=ultrices&justo=aliquet&lacinia=maecenas&eget=leo&tincidunt=odio&eget=condimentum&tempus=id&vel=luctus&pede=nec&morbi=molestie&porttitor=sed&lorem=justo&id=pellentesque&ligula=viverra&suspendisse=pede&ornare=ac&consequat=diam&lectus=cras&in=pellentesque&est=volutpat&risus=dui&auctor=maecenas&sed=tristique&tristique=est&in=et&tempus=tempus&sit=semper&amet=est&sem=quam&fusce=pharetra&consequat=magna&nulla=ac&nisl=consequat&nunc=metus&nisl=sapien&duis=ut&bibendum=nunc&felis=vestibulum&sed=ante&interdum=ipsum', 'Created', 6, 2, 6);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-21', 28, 'http://china.com.cn/lobortis/est/phasellus/sit/amet.xml?elit=urna&proin=pretium&risus=nisl&praesent=ut&lectus=volutpat&vestibulum=sapien&quam=arcu&sapien=sed&varius=augue&ut=aliquam&blandit=erat&non=volutpat&interdum=in&in=congue&ante=etiam&vestibulum=justo&ante=etiam&ipsum=pretium&primis=iaculis&in=justo&faucibus=in&orci=hac&luctus=habitasse&et=platea&ultrices=dictumst&posuere=etiam&cubilia=faucibus&curae=cursus&duis=urna&faucibus=ut&accumsan=tellus&odio=nulla&curabitur=ut&convallis=erat&duis=id&consequat=mauris&dui=vulputate&nec=elementum&nisi=nullam&volutpat=varius&eleifend=nulla&donec=facilisi&ut=cras&dolor=non&morbi=velit&vel=nec&lectus=nisi&in=vulputate&quam=nonummy&fringilla=maecenas&rhoncus=tincidunt&mauris=lacus&enim=at&leo=velit&rhoncus=vivamus&sed=vel&vestibulum=nulla&sit=eget&amet=eros&cursus=elementum&id=pellentesque&turpis=quisque&integer=porta&aliquet=volutpat&massa=erat&id=quisque&lobortis=erat&convallis=eros&tortor=viverra&risus=eget&dapibus=congue&augue=eget&vel=semper&accumsan=rutrum&tellus=nulla', 'Created', 7, 3, 7);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-16', 12, 'http://dailymotion.com/nibh/in.xml?consequat=id&lectus=lobortis&in=convallis&est=tortor&risus=risus&auctor=dapibus&sed=augue&tristique=vel&in=accumsan&tempus=tellus&sit=nisi', 'Created', 8, 4, 8);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-23', 29, 'http://skyrock.com/pede.html?lectus=vivamus&vestibulum=vel&quam=nulla&sapien=eget&varius=eros&ut=elementum&blandit=pellentesque&non=quisque&interdum=porta&in=volutpat&ante=erat&vestibulum=quisque&ante=erat&ipsum=eros&primis=viverra&in=eget&faucibus=congue&orci=eget&luctus=semper&et=rutrum&ultrices=nulla&posuere=nunc&cubilia=purus&curae=phasellus&duis=in&faucibus=felis&accumsan=donec&odio=semper&curabitur=sapien&convallis=a&duis=libero&consequat=nam&dui=dui&nec=proin&nisi=leo&volutpat=odio&eleifend=porttitor&donec=id&ut=consequat&dolor=in&morbi=consequat', 'Created', 9, 1, 9);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-16', 8, 'http://whitehouse.gov/pellentesque/eget/nunc.js?venenatis=pellentesque&lacinia=at&aenean=nulla&sit=suspendisse&amet=potenti&justo=cras&morbi=in&ut=purus&odio=eu&cras=magna&mi=vulputate&pede=luctus&malesuada=cum&in=sociis&imperdiet=natoque&et=penatibus&commodo=et&vulputate=magnis', 'Created', 10, 2, 10);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-16', 27, 'http://1und1.de/nisl/aenean.aspx?venenatis=integer&turpis=pede&enim=justo&blandit=lacinia&mi=eget&in=tincidunt&porttitor=eget&pede=tempus&justo=vel&eu=pede&massa=morbi&donec=porttitor&dapibus=lorem&duis=id&at=ligula&velit=suspendisse&eu=ornare&est=consequat&congue=lectus', 'Created', 1, 3, 11);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-18', 7, 'https://cbsnews.com/consequat/in/consequat.png?nunc=nec&rhoncus=euismod&dui=scelerisque&vel=quam&sem=turpis&sed=adipiscing&sagittis=lorem&nam=vitae&congue=mattis&risus=nibh&semper=ligula&porta=nec&volutpat=sem&quam=duis&pede=aliquam&lobortis=convallis&ligula=nunc&sit=proin&amet=at&eleifend=turpis&pede=a&libero=pede', 'Created', 2, 4, 12);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-18', 16, 'https://huffingtonpost.com/ac/diam/cras/pellentesque/volutpat/dui/maecenas.png?nulla=malesuada&elit=in&ac=imperdiet&nulla=et&sed=commodo&vel=vulputate&enim=justo&sit=in&amet=blandit&nunc=ultrices&viverra=enim&dapibus=lorem&nulla=ipsum&suscipit=dolor&ligula=sit&in=amet&lacus=consectetuer', 'Created', 3, 1, 13);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-17', 8, 'https://jugem.jp/sapien/iaculis/congue/vivamus/metus/arcu/adipiscing.jsp?sagittis=molestie&dui=sed&vel=justo&nisl=pellentesque&duis=viverra&ac=pede&nibh=ac&fusce=diam&lacus=cras&purus=pellentesque&aliquet=volutpat&at=dui&feugiat=maecenas&non=tristique&pretium=est&quis=et&lectus=tempus&suspendisse=semper&potenti=est&in=quam&eleifend=pharetra&quam=magna&a=ac&odio=consequat&in=metus&hac=sapien&habitasse=ut&platea=nunc&dictumst=vestibulum&maecenas=ante&ut=ipsum&massa=primis&quis=in&augue=faucibus&luctus=orci&tincidunt=luctus&nulla=et&mollis=ultrices&molestie=posuere&lorem=cubilia&quisque=curae&ut=mauris&erat=viverra&curabitur=diam&gravida=vitae&nisi=quam&at=suspendisse&nibh=potenti&in=nullam&hac=porttitor&habitasse=lacus&platea=at&dictumst=turpis&aliquam=donec&augue=posuere&quam=metus&sollicitudin=vitae&vitae=ipsum&consectetuer=aliquam&eget=non&rutrum=mauris&at=morbi&lorem=non&integer=lectus&tincidunt=aliquam&ante=sit&vel=amet&ipsum=diam&praesent=in&blandit=magna&lacinia=bibendum&erat=imperdiet&vestibulum=nullam&sed=orci&magna=pede&at=venenatis&nunc=non&commodo=sodales&placerat=sed&praesent=tincidunt&blandit=eu&nam=felis&nulla=fusce&integer=posuere&pede=felis', 'Created', 4, 2, 14);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-22', 12, 'http://amazonaws.com/risus/dapibus/augue/vel/accumsan.xml?sed=vel&vestibulum=ipsum&sit=praesent&amet=blandit&cursus=lacinia&id=erat&turpis=vestibulum&integer=sed&aliquet=magna&massa=at&id=nunc&lobortis=commodo&convallis=placerat&tortor=praesent&risus=blandit&dapibus=nam&augue=nulla&vel=integer&accumsan=pede&tellus=justo&nisi=lacinia&eu=eget&orci=tincidunt&mauris=eget&lacinia=tempus&sapien=vel&quis=pede&libero=morbi&nullam=porttitor&sit=lorem&amet=id&turpis=ligula&elementum=suspendisse&ligula=ornare&vehicula=consequat&consequat=lectus&morbi=in&a=est&ipsum=risus&integer=auctor&a=sed&nibh=tristique&in=in&quis=tempus&justo=sit&maecenas=amet&rhoncus=sem&aliquam=fusce&lacus=consequat&morbi=nulla&quis=nisl&tortor=nunc&id=nisl&nulla=duis&ultrices=bibendum&aliquet=felis&maecenas=sed&leo=interdum&odio=venenatis&condimentum=turpis&id=enim&luctus=blandit&nec=mi&molestie=in&sed=porttitor&justo=pede&pellentesque=justo&viverra=eu&pede=massa&ac=donec&diam=dapibus&cras=duis&pellentesque=at&volutpat=velit&dui=eu&maecenas=est&tristique=congue&est=elementum&et=in&tempus=hac', 'Created', 5, 3, 15);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-23', 14, 'http://prlog.org/curae.json?nibh=turpis&ligula=adipiscing&nec=lorem&sem=vitae&duis=mattis&aliquam=nibh&convallis=ligula&nunc=nec&proin=sem&at=duis&turpis=aliquam&a=convallis&pede=nunc&posuere=proin&nonummy=at&integer=turpis&non=a&velit=pede&donec=posuere&diam=nonummy&neque=integer&vestibulum=non&eget=velit&vulputate=donec&ut=diam&ultrices=neque&vel=vestibulum&augue=eget&vestibulum=vulputate&ante=ut&ipsum=ultrices&primis=vel&in=augue&faucibus=vestibulum&orci=ante&luctus=ipsum&et=primis&ultrices=in&posuere=faucibus&cubilia=orci&curae=luctus&donec=et&pharetra=ultrices&magna=posuere&vestibulum=cubilia&aliquet=curae&ultrices=donec&erat=pharetra&tortor=magna&sollicitudin=vestibulum&mi=aliquet&sit=ultrices&amet=erat&lobortis=tortor&sapien=sollicitudin', 'Created', 6, 4, 16);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-21', 15, 'https://netlog.com/ipsum/aliquam/non/mauris/morbi.png?duis=in&consequat=tempor&dui=turpis&nec=nec&nisi=euismod&volutpat=scelerisque&eleifend=quam&donec=turpis&ut=adipiscing&dolor=lorem&morbi=vitae&vel=mattis&lectus=nibh&in=ligula&quam=nec&fringilla=sem&rhoncus=duis&mauris=aliquam&enim=convallis&leo=nunc&rhoncus=proin&sed=at&vestibulum=turpis&sit=a&amet=pede&cursus=posuere&id=nonummy', 'Created', 7, 1, 17);
insert into Interview (startDate, duration, accessURL, status, employee_id, staff_member_id, job_application_id) values ('2020-07-22', 11, 'https://typepad.com/rhoncus/dui/vel/sem/sed/sagittis/nam.jsp?nam=massa&dui=quis&proin=augue&leo=luctus&odio=tincidunt&porttitor=nulla&id=mollis&consequat=molestie&in=lorem&consequat=quisque&ut=ut', 'Created', 8, 2, 18);


INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),3,1);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('24-06-2021','DD-MM-YYYY'),7,1);

INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('25-06-2021','DD-MM-YYYY'),3,2);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('25-06-2021','DD-MM-YYYY'),4,2);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('25-06-2021','DD-MM-YYYY'),5,2);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('25-06-2021','DD-MM-YYYY'),6,2);

INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),7,3);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),8,3);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),9,3);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),10,3);

INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),8,4);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('24-06-2021','DD-MM-YYYY'),12,4);

INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),1,6);

INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),1,7);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),2,7);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),6,7);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),9,7);
INSERT INTO Job_Application (status, date_application, employee_id, job_offer_id) values 
('Pending Review',TO_DATE('23-06-2021','DD-MM-YYYY'),12,7);

insert into Review (totalScore, employee_id, employer_id, application_id) values (18, 1, 1, 1);
insert into Review (totalScore, employee_id, employer_id, application_id) values (17, 2, 2, 2);
insert into Review (totalScore, employee_id, employer_id, application_id) values (6, 3, 3, 3);
insert into Review (totalScore, employee_id, employer_id, application_id) values (14, 4, 4, 4);
insert into Review (totalScore, employee_id, employer_id, application_id) values (13, 5, 1, 5);
insert into Review (totalScore, employee_id, employer_id, application_id) values (4, 6, 2, 6);
insert into Review (totalScore, employee_id, employer_id, application_id) values (14, 7, 3, 7);
insert into Review (totalScore, employee_id, employer_id, application_id) values (17, 8, 4, 8);
insert into Review (totalScore, employee_id, employer_id, application_id) values (4, 9, 1, 9);
insert into Review (totalScore, employee_id, employer_id, application_id) values (12, 10, 2, 10);
insert into Review (totalScore, employee_id, employer_id, application_id) values (17, 1, 3, 11);
insert into Review (totalScore, employee_id, employer_id, application_id) values (14, 2, 4, 12);
insert into Review (totalScore, employee_id, employer_id, application_id) values (2, 3, 1, 13);
insert into Review (totalScore, employee_id, employer_id, application_id) values (7, 4, 2, 14);
insert into Review (totalScore, employee_id, employer_id, application_id) values (2, 5, 3, 15);
insert into Review (totalScore, employee_id, employer_id, application_id) values (4, 6, 4, 16);
insert into Review (totalScore, employee_id, employer_id, application_id) values (17, 7, 1, 17);
insert into Review (totalScore, employee_id, employer_id, application_id) values (4, 8, 2, 18);

insert into Question(name, score, review_id) values ("Do you have enough independence to carry out your tasks?", 4, 1);
insert into Question(name, score, review_id) values ("Do you feel stagnant?", 4, 2);
insert into Question(name, score, review_id) values ("What would you implement in the company that you have seen in other companies?", 4, 3);
insert into Question(name, score, review_id) values ("Do you have enough information to perform your tasks effectively?", 4, 4);
insert into Question(name, score, review_id) values ("How is the balance between your personal life and your work?", 4, 5);
insert into Question(name, score, review_id) values ("Do you think you are productive telecommuting?", 4, 6);
insert into Question(name, score, review_id) values ("How important is salary to you?", 4, 7);
insert into Question(name, score, review_id) values ("What do you consider to be your greatest work achievement and why?", 4, 8);
insert into Question(name, score, review_id) values ("Is there a skill you want to develop or something you want to learn? As you do?", 4, 9);
insert into Question(name, score, review_id) values ("What would your dream job?", 4, 10);
insert into Question(name, score, review_id) values ("If you had to define your work style in one word, what would it be?", 4, 11);
insert into Question(name, score, review_id) values ("What do you like to do when you are not working?", 4, 12);
insert into Question(name, score, review_id) values ("What struck you the most about the position?", 4, 13);
insert into Question(name, score, review_id) values ("What does work mean to you?", 4, 14);
insert into Question(name, score, review_id) values ("If we select you for that position, what actions will you take during the first week to improve?", 4, 15);
