insert into Users (document, username, password, email, status) values ('0980019087', 'lgrowden1', 'VoWbDvkNBebm', 'mburgher1@telegraph.co.uk', 'Active');
insert into Users (document, username, password, email, status) values ('2531938184', 'hdeboick2', 'FdXLo3jJ', 'knowland2@hubpages.com', 'Active');
insert into Users (document, username, password, email, status) values ('0872229777', 'mmarjot3', 'EA6VNeyjA', 'lwonfar3@unicef.org', 'Active');
insert into Users (document, username, password, email, status) values ('3603657853', 'hmusprat4', '4ByxHAj', 'lkullmann4@chronoengine.com', 'Active');
insert into Users (document, username, password, email, status) values ('3359654471', 'ldunseith5', '8v0iG5bAsAy', 'csalkild5@google.cn', 'Active');
insert into Users (document, username, password, email, status) values ('0540379034', 'ochaves6', 'B0yDAWPFf9q', 'oingold6@elegantthemes.com', 'Active');
insert into Users (document, username, password, email, status) values ('9340058267', 'gdomini7', 'fQuTqL3RSRYc', 'fallred7@latimes.com', 'Inactive');
insert into Users (document, username, password, email, status) values ('1595894233', 'ytrustrie8', 'QlCclnEeA', 'etallyn8@vimeo.com', 'Active');
insert into Users (document, username, password, email, status) values ('8844372142', 'mbalogh9', 'DnIZfIbI', 'strevain9@sciencedirect.com', 'Active');
insert into Users (document, username, password, email, status) values ('3735983901', 'slightbownea', '9HEDzX4L4Xbo', 'cothena@yahoo.co.jp', 'Active');
insert into Users (document, username, password, email, status) values ('9366429424', 'ijodlkowskib', 'LwFIM7hRVk', 'jtorresb@artisteer.com', 'Active');
insert into Users (document, username, password, email, status) values ('7461336479', 'cshakeladyc', 'bdH59L', 'romalleyc@webeden.co.uk', 'Active');
insert into Users (document, username, password, email, status) values ('5543644701', 'alinseyd', '6OQIm0IsjzAd', 'ocloggd@narod.ru', 'Inactive');
insert into Users (document, username, password, email, status) values ('0495915637', 'ahutcheone', 'VdNfV1', 'rfuenteze@wikispaces.com', 'Active');
insert into Users (document, username, password, email, status) values ('8127714909', 'jbakesf', 'wrXmoRa31po', 'jbrewerf@moonfruit.com', 'Active');
insert into Users (document, username, password, email, status) values ('4683414945', 'tmaletrattg', 'zCh99zjY', 'tclaessensg@dion.ne.jp', 'Active');
insert into Users (document, username, password, email, status) values ('1382374135', 'cbarmeh', 'EVrrzDB4IV9G', 'dtoomerh@chron.com', 'Active');
insert into Users (document, username, password, email, status) values ('8333830455', 'rhoferi', 'pqBVn6aUBd', 'pliveni@vinaora.com', 'Active');
insert into Users (document, username, password, email, status) values ('6379461183', 'dnaughtonj', 'JWujCtKiX7', 'pmacsorleyj@cnet.com', 'Active');
insert into Users (document, username, password, email, status) values ('1234567890', 'Grupoi', 'grupoi', 'grupoi@ucab.com', 'Active');

insert into Employer (name, user_id) values ('Mudo', 1);
insert into Employer (name, user_id) values ('Flashspan', 2);
insert into Employer (name, user_id) values ('Linkbridge', 3);
insert into Employer (name, user_id) values ('Aimbu', 4);

insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Bili', 'M', 'Gearalt', 'Koppe', 'Hambleton', '05/08/1966', 5);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Rudolfo', 'M', 'Lotta', 'Pershouse', 'Luckey', '21/06/1973', 6);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Andrey', 'F', null, 'Mor', 'Blissett', '14/06/1995', 7);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Darrelle', 'F', 'Cherise', 'Linnell', 'Harker', '02/11/1960', 8);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Sarge', 'F', 'Klara', 'Galvan', 'Duffin', '20/02/1974', 9);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Hillie', 'M', 'Coreen', 'Durdan', 'Roaf', '08/12/1964', 10);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Bruno', 'F', 'Drucie', 'Popelay', 'Ramet', '02/03/1999', 11);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Albina', 'F', 'Portia', 'Eskrick', 'Broinlich', '20/07/1985', 12);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Petra', 'M', 'Etan', 'Gitthouse', 'Drillingcourt', '07/05/1981', 13);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Haley', 'F', 'Elwood', 'Illston', 'O''Rourke', '09/01/1971', 14);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Byron', 'F', 'Catherin', 'Cowins', 'Vasechkin', '16/09/1967', 15);
insert into Employee (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Blinnie', 'M', 'Carmencita', 'Aleksandrikin', 'Gatchel', '06/01/1993', 16);

insert into Staff_Member (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Shelagh', 'F', 'Bride', 'Foxley', 'Carik', '21/08/1988', 17);
insert into Staff_Member (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Ranee', 'M', 'Joey', 'Thornley', 'Malden', '03/09/1987', 18);
insert into Staff_Member (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Emelia', 'F', 'Krishna', 'Schoolcroft', 'Edinburough', '23/06/1984', 19);
insert into Staff_Member (name, gender, second_name, lastname, second_lastname , birth_date, user_id) values ('Zebulon', 'F', 'Pat', 'Haville', 'Giorgeschi', '24/09/1978', 20);
